name: novena_lorenzo
description: An offline novena app to St. Lorenzo Ruiz
publish_to: 'none'
version: 1.0.7+9

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  path_provider: ^2.1.5
  just_audio: ^0.9.42
  youtube_player_flutter: ^9.1.1
  connectivity_plus: ^6.1.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  flutter_timezone: ^3.0.1
  flutter_native_splash: ^2.4.3
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lib/data/
    - assets/himno.mp3
